[project]
name = "openmedic"
dynamic = ["version"]
description = ""
readme = "README.md"
requires-python = "==3.10.18"
dependencies = [
    "click>=8.2.1",
    "opencv-python>=4.11.0.86",
    "pycocotools>=2.0.8",
    "pyyaml>=6.0.2",
    "torch>=2.2.2",
    "torchvision>=0.17.2"
]


[project.scripts]
openmedic = "openmedic.cli.cli_management:cli"


[tool.setuptools.dynamic]
version = {attr = "openmedic.__version__"}

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
