transform:
  Resize:
    target_w: 512
    target_h: 512
    interpolation: INTER_LINEAR

model:
  name: UNet
  params:
    n_channels: 3
    n_classes: 2
  model_checkpoint: "/home/nathanngo/projects/KC-2025/segmentation/best_202050604.pth"

pipeline:
  input_path: "/mnt/data_lab513/kc/fundus/fives-coco/images/792_N.png"
  # mask_threshold: 0.3
  output_dir: ""
  batch_size: 1
  engine: cuda
  verbose: true
