name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Black
        uses: psf/black@stable
        with:
          options: --check --diff
          python-version: 3.10.18
      - name: Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check --fix
